apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # get encoded values with `echo -n 'value' | base64`
  username: <base64-encoded-username>
  password: <base64-encoded-password>
